---
abstract: 'The Qgoda Static Site Generator'
author:
  - 'Guido Flohr <guido.flohr@cantanea.com>'
build_requires:
  Carp: '0'
  Git::Repository: '1.321'
  Locale::PO: '0'
  Test::More: '0'
  Time::Local: '0'
  autodie: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Qgoda
requires:
  AnyEvent: '0'
  AnyEvent::Filesys::Notify: '1.23'
  AnyEvent::Handle: '0'
  AnyEvent::Loop: '0'
  Archive::Extract: '0'
  Cpanel::JSON::XS: '0'
  Cwd: '0'
  Data::Dumper: '0'
  Data::Walk: '2.00'
  Date::Parse: '0'
  Encode: '2.12'
  Exporter: '0'
  ExtUtils::MakeMaker: '7.1101'
  File::Basename: '0'
  File::Copy: '0'
  File::Copy::Recursive: '0'
  File::Find: '0'
  File::Globstar: '0'
  File::Globstar::ListMatch: '0'
  File::HomeDir: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
  Filter::Util::Call: '0'
  Getopt::Long: '2.36'
  Git: '0'
  HTML::Parser: '0'
  HTML::TreeBuilder: '0'
  IO::File: '0'
  IO::Handle: '0'
  IO::Interactive: '0'
  IPC::Open3: '0'
  IPC::Signal: '0'
  Inline: '0'
  JSON: '2.0'
  JSON::PP: '0'
  JavaScript::Duktape::XS: '0.000074'
  LWP::UserAgent: '0'
  List::Util: '1.45'
  Locale::Messages: '0'
  Locale::TextDomain: '1.30'
  Locale::Util: '0'
  Locale::XGettext: '0.7'
  Locale::gettext_dumb: '0'
  MIME::Base64: '0'
  POSIX: '0'
  Pod::Perldoc: '0'
  Scalar::Util: '0'
  Storable: '0'
  Symbol: '0'
  Template: '0'
  Template::Constants: '0'
  Template::Plugin: '0'
  Template::Plugin::Filter: '0'
  Template::Plugin::Gettext: '0.7'
  Template::Provider: '0'
  Template::Stash: '0'
  Term::ANSIColor: '0'
  Text::Markdown: '0'
  Text::Markdown::Hoedown: '0'
  Text::Unidecode: '0'
  Time::HiRes: '0'
  URI: '0'
  URI::Escape: '0'
  URI::file: '0'
  URI::git: '0.02'
  YAML: '0'
  YAML::XS: '0.67'
  base: '0'
  boolean: '0'
  common::sense: '0'
  constant: '0'
  integer: '0'
  overload: '0'
  perl: '5.018'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/gflohr/qgoda/issues
  homepage: http://www.qgoda.net/
  repository: git://github.com/gflohr/qgoda.git
version: 0.9.8
x_generated_by_perl: v5.28.0
x_serialization_backend: 'YAML::Tiny version 1.73'
