---
analyzers:
- GuidedTour
case-sensitive: false
compare-output: true
defaults:
- files:
  - /*/**
  - '!/en/'
  values:
    translate:
    - title
    - description
    - image_alt
    - button
    - dateFormat
    - readMore
- files:
  - /en
  - /_includes/en
  values:
    lingua: en
- files:
  - /de
  - /_includes/de
  values:
    lingua: de
- files: /*/docs/**
  values:
    tour: doc
    type: doc
    view: docs.html
- files: /*/talks/**
  values:
    type: talk
    view: talks.html
- files: /*/talks/dpw-2018/**
  values:
    tour: talk-dpw-2018
- files: /*/news/**
  values:
    author: Guido Flohr
    navsection: news
    type: post
- files:
  - index.md
  - index.html
  values:
    priority: -999
    type: page
exclude:
- /node_modules
- /package.json
- /webpack.config.js
- /yarn.lock
- /TODO
- /LocaleData
- /postcss.config.js
- /COPYING
- /README.md
exclude_watch:
- /assets
- '!/_timestamp.json'
- '!/_includes'
front_matter_placeholder: "[% '' %]\n"
generator: Qgoda 0.9.2 (http://www.qgoda.net/)
helpers:
  browser-sync:
  - yarn server
  yarn:
  - yarn start
index: index
latency: 0.5
legal:
  city: configure legal.name in _localconfig.yaml or _config.yaml
  copyright_uri: configure legal.name in _localconfig.yaml or _config.yaml
  copyright_year: configure legal.name in _localconfig.yaml or _config.yaml
  email: configure legal.email in _localconfig.yaml or _config.yaml
  id: configure legal.name in _localconfig.yaml or _config.yaml
  manager: configure legal.manager in _localconfig.yaml or _config.yaml
  name: configure legal.name in _localconfig.yaml or _config.yaml
  phone: configure legal.phone in _localconfig.yaml or _config.yaml
  responsible: configure legal.responsible in _localconfig.yaml or _config.yaml
  street: configure legal.name in _localconfig.yaml or _config.yaml
  vat-id: configure legal.name in _localconfig.yaml or _config.yaml
linguas:
- en
- de
link_score: 5
location: /{directory}/{basename}/{index}{suffix}
no_scm:
- /assets
paths:
  plugins: _plugins
  po: _po
  site: /Users/guido/perl/qgoda/_site
  timestamp: _timestamp
  views: _views
permalink: '{significant-path}'
po:
  copyright_holder: cantanea EOOD <http://www.cantanea.com/>
  from_code: utf-8
  mdextra:
  - /_includes/**
  msgfmt: msgfmt
  msgid_bugs_address: Guido Flohr <guido.flohr@cantanea.com>
  msgmerge: msgmerge
  qgoda:
  - perl
  - -I/Users/guido/perl/qgoda/lib
  - /Users/guido/perl/qgoda/bin/qgoda
  refresh: 0
  reload: 1
  textdomain: net.qgoda.www
  tt2:
  - _views
  views:
  - /_views/**
  - '!/_views/raw'
  - '!/_views/functions/**'
  xgettext: xgettext
  xgettext_tt2: xgettext-tt2
processors:
  chains:
    html:
      modules:
      - TT2
      - HTMLCleaner
      - HTMLFilter
    markdown:
      modules:
      - TT2
      - Hoedown
      suffix: html
      wrapper: html
    xml:
      modules:
      - TT2
      - Strip
  options:
    HTMLFilter:
    - AnchorTarget
    - Generator
    - CleanUp
    - - TOC
      - content_tag
      - qgoda-content
      - toc_tag
      - qgoda-toc
      - start
      - 2
      - end
      - 6
      - template
      - components/toc.html
    Markdown: {}
    TT2: {}
  triggers:
    htm: html
    html: html
    md: markdown
    mdown: markdown
    mdwn: markdown
    mkd: markdown
    mkdn: markdown
    xml: xml
scm: git
srcdir: /Users/guido/perl/qgoda
taxonomies:
  categories: 3
  doc-section: 1
  links: 1
  name: 1
  tags: 2
title: Qgoda
view: default.html
