---
case-sensitive: 0
compare_output: 1
defaults: []
exclude: []
exclude_watch: []
front_matter_placeholder: "[% '' %]\n"
generator: Qgoda 0.9.2 (http://www.qgoda.net/)
helpers: {}
index: index
latency: 0.5
link_score: 5
location: /{directory}/{basename}/{index}{suffix}
no_scm: []
paths:
  plugins: _plugins
  po: _po
  site: /Users/guido/perl/qgoda/_site
  timestamp: _timestamp
  views: _views
permalink: '{significant-path}'
po:
  copyright_holder: Set config.po.copyright_holder in _config.yaml
  from_code: utf-8
  msgfmt: msgfmt
  msgid_bugs_address: Set config.po.msgid_bugs_address in _config.yaml
  msgmerge: msgmerge
  qgoda: qgoda
  refresh: 0
  tt2:
  - _views
  xgettext: xgettext
  xgettext_tt2: xgettext-tt2
processors:
  chains:
    html:
      modules:
      - TT2
      - Strip
      - HTMLFilter
    markdown:
      modules:
      - TT2
      - Strip
      - Markdown
      suffix: html
      wrapper: html
    xml:
      modules:
      - TT2
      - Strip
  options:
    HTMLFilter:
    - AnchorTarget
    - Generator
    - CleanUp
    - - TOC
      - content_tag
      - qgoda-content
      - toc_tag
      - qgoda-toc
      - start
      - 2
      - end
      - 6
      - template
      - components/toc.html
    Markdown: {}
    TT2: {}
  triggers:
    htm: html
    html: html
    md: markdown
    mdown: markdown
    mdwn: markdown
    mkd: markdown
    mkdn: markdown
    xml: xml
srcdir: /Users/guido/perl/qgoda
taxonomies:
  categories: 3
  links: 1
  tags: 2
title: A New Qgoda Powered Site
view: default.html
